# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Models Not Bottles
description:      'Markets, data science, and software'

url:              fordmanbell.github.io
baseurl:          

author:
  name:           'Fordman Bell'

paginate:         5

github:
  repo:           https://github.com/fordmanbell


plugins:
  - jekyll-paginate
  - jekyll-gist
